version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: fomo3d
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: